# Generated by Django 4.2.5 on 2023-10-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_history',
            field=models.ManyToManyField(related_name='watched_by', to='app.anime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='app.anime'),
        ),
    ]
